# Generated by Django 5.1.1 on 2024-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('rating', models.PositiveSmallIntegerField()),
                ('discount', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
